In [2]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


Answer->

In Python, the term "array" usually refers to a NumPy array, which is a specific type of data structure used for numerical operations. On the other hand, a "list" is a built-in Python data type that can hold elements of any type.

To check the data types of variables list_ and array_list, we can use the type() function in Python

In [7]:
import numpy as np

list_ = ['1','2','3','4','5'] #class 'list'

array_list = np.array(object = list_) #'numpy.ndarray'
print(type(array_list),type(list_))


<class 'numpy.ndarray'> <class 'list'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


Answer->



In [12]:
import numpy as np

list_ = ['1','2','3','4','5'] #class 'list'
print(" fro list_ ")
array_list = np.array(object = list_) #'numpy.ndarray'
for i in  list_:
    print(type(i))
    
print(" fro array_list ")
for i in array_list:
    print(type(i))



 fro list_ 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
 fro array_list 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer->

Yes, there will be a difference in the data type of the elements present in list_ and array_list after applying the given changes. The np.array() function with the dtype=int argument will convert each string element in list_ to an integer data type and create a new NumPy array array_list with the same elements but with integer data type.

The dtype argument in the np.array() function specifies the data type of the array elements. When we set dtype=int, it means that all elements in the array will be cast to the integer data type. This is a common technique used to convert arrays with mixed data types into arrays with a uniform data type.

In [13]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_, dtype = int)
for i in  list_:
    print(type(i))
    
print(" fro array_list ")
for i in array_list:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
 fro array_list 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size



In [19]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print(f" <i> for shape function",num_array.shape) # shape (rows , column ) = (2,3)
print(f" <ii> for size function",num_array.size)  # size = rows*column = 6

 <i> for shape function (2, 3)
 <ii> for size function 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Answer->


In [29]:
import numpy as np 

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [23]:
import numpy as np 
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
# for same 

import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
